# Generated by Django 5.2.6 on 2025-09-23 06:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("compose", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name="score",
            old_name="created_at",
            new_name="played_at",
        ),
        migrations.RenameField(
            model_name="score",
            old_name="points",
            new_name="score",
        ),
        migrations.RemoveField(
            model_name="score",
            name="name",
        ),
        migrations.AddField(
            model_name="score",
            name="user",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
    ]
