# Generated by Django 4.2.24 on 2025-10-03 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("compose", "0002_rename_created_at_score_played_at_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SongPattern",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("beginner", "初級"),
                            ("intermediate", "中級"),
                            ("advanced", "上級"),
                        ],
                        max_length=20,
                    ),
                ),
                ("pattern", models.JSONField()),
            ],
        ),
    ]
